# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\x12\x08messages\"T\n\x0fMessageToServer\x12\x0e\n\x06opcode\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x05 \x01(\t\x12\x0e\n\x06target\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\"\x1c\n\tServerLog\x12\x0f\n\x07message\x18\x01 \x01(\t2V\n\x06Server\x12L\n\x18ReceiveMessageFromClient\x12\x19.messages.MessageToServer\x1a\x13.messages.ServerLog\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGETOSERVER._serialized_start=28
  _MESSAGETOSERVER._serialized_end=112
  _SERVERLOG._serialized_start=114
  _SERVERLOG._serialized_end=142
  _SERVER._serialized_start=144
  _SERVER._serialized_end=230
# @@protoc_insertion_point(module_scope)
